name: MobSF Analysis

on:
  push:
    branches: [ 'topic/devops' ]
  pull_request:
    branches: [ main, staging ]

jobs:
  mobsf-scan:
    name: MobSF Security
    
    runs-on: ubuntu-latest
    
    permissions:
      contents: read
      security-events: write
      pull-requests: write
      
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install PYTHON
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install MOB-SF
        run: pip install mobsfscan

      - name: Analysis
        id: scan
        run: |
          mobsfscan --sarif --output mobsfscan.sarif . --no-fail
          
          if [ -f "mobsfscan.sarif" ]; then
            echo "SARIF report generated successfully."
            
            FINDINGS_COUNT=$(jq '.runs[0].results // [] | length' mobsfscan.sarif)
            echo "Number of findings: $FINDINGS_COUNT"
            if [ "$FINDINGS_COUNT" -gt 0 ]; then
              echo "FAILED=true" >> $GITHUB_OUTPUT
            else
              echo "FAILED=false" >> $GITHUB_OUTPUT
            fi
          else
            echo "SARIF file was not created."
            echo "FAILED=true" >> $GITHUB_OUTPUT
          fi

      - name: Output in Security
        uses: github/codeql-action/upload-sarif@v3
        if: always()
        with:
          sarif_file: mobsfscan.sarif
          
      - name: Output as Artifact
        uses: actions/upload-artifact@v4
        with:
          name: mobsfscan-sarif
          path: mobsfscan.sarif

      - name: Triage
        if: steps.scan.outputs.FAILED == 'true'
        run: |
          echo "Log:"
          echo "❌ MobSF scan failed due to security findings or an error."
          echo "   Check the logs and the uploaded SARIF report.          "